-- Full schema for the JSP project.
-- Run this as the same Oracle user configured in META-INF/context.xml.
-- The base ADMIN/CATEGORY/MEMBER/PRODUCT/PRODUCT_IMAGE structure follows the
-- provided WEB DDL, without hard-coded schema/table-space clauses.

CREATE TABLE admin (
    login_id VARCHAR2(50 BYTE),
    password VARCHAR2(255 BYTE),
    name VARCHAR2(50 BYTE),
    created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE category (
    category_id NUMBER,
    category_name VARCHAR2(50 BYTE),
    is_active CHAR(1 BYTE)
);

CREATE TABLE member (
    login_id VARCHAR2(50 BYTE),
    password VARCHAR2(255 BYTE),
    nickname VARCHAR2(50 BYTE),
    phone VARCHAR2(20 BYTE),
    region VARCHAR2(100 BYTE),
    profile_text VARCHAR2(255 BYTE),
    manner_score NUMBER(3,1) DEFAULT 36.5,
    status VARCHAR2(20 BYTE) DEFAULT 'ACTIVE',
    created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6)
);

CREATE TABLE product (
    product_id NUMBER,
    seller_id VARCHAR2(20 BYTE),
    category_id NUMBER,
    title VARCHAR2(150 BYTE),
    content CLOB,
    price NUMBER,
    region VARCHAR2(100 BYTE),
    status VARCHAR2(20 BYTE) DEFAULT 'SALE',
    view_count NUMBER,
    is_deleted CHAR(1 BYTE) DEFAULT 'N',
    created_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
    updated_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP
);

CREATE TABLE product_image (
    image_id NUMBER,
    product_id NUMBER,
    origin_name VARCHAR2(255 BYTE),
    save_name VARCHAR2(255 BYTE),
    image_path VARCHAR2(500 BYTE),
    is_main CHAR(1 BYTE) DEFAULT 'N',
    created_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP
);

ALTER TABLE admin ADD CONSTRAINT admin_pk PRIMARY KEY (login_id);
ALTER TABLE admin MODIFY (login_id NOT NULL);
ALTER TABLE admin MODIFY (password NOT NULL);
ALTER TABLE admin MODIFY (name NOT NULL);

ALTER TABLE category MODIFY (category_id NOT NULL);
ALTER TABLE category MODIFY (category_name NOT NULL);
ALTER TABLE category ADD CONSTRAINT category_pk PRIMARY KEY (category_id);

ALTER TABLE member ADD CONSTRAINT member_pk PRIMARY KEY (login_id);
ALTER TABLE member MODIFY (login_id NOT NULL);
ALTER TABLE member MODIFY (password NOT NULL);
ALTER TABLE member MODIFY (nickname NOT NULL);
ALTER TABLE member MODIFY (region NOT NULL);
ALTER TABLE member ADD CONSTRAINT chk_member_status CHECK (status IN ('ACTIVE','STOPPED','WITHDRAWN'));
ALTER TABLE member ADD CONSTRAINT uq_member_phone UNIQUE (phone);

ALTER TABLE product MODIFY (category_id NOT NULL);
ALTER TABLE product MODIFY (title NOT NULL);
ALTER TABLE product MODIFY (content NOT NULL);
ALTER TABLE product MODIFY (price NOT NULL);
ALTER TABLE product MODIFY (region NOT NULL);
ALTER TABLE product ADD CONSTRAINT chk_product_status CHECK (status IN ('SALE','RESERVED','SOLD','HIDDEN'));
ALTER TABLE product MODIFY (product_id NOT NULL);
ALTER TABLE product ADD CONSTRAINT product_pk PRIMARY KEY (product_id);
ALTER TABLE product ADD CONSTRAINT fk_product_member FOREIGN KEY (seller_id)
    REFERENCES member (login_id);

ALTER TABLE product_image ADD CONSTRAINT product_image_pk PRIMARY KEY (image_id);
ALTER TABLE product_image MODIFY (product_id NOT NULL);
ALTER TABLE product_image ADD CONSTRAINT fk_product_image_product FOREIGN KEY (product_id)
    REFERENCES product (product_id) ON DELETE CASCADE;

-- Objects required by the current JSP code but missing from the provided DDL.
CREATE SEQUENCE seq_product START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_image START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE favorite (
    favorite_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    member_id VARCHAR2(20 BYTE) NOT NULL,
    product_id NUMBER NOT NULL,
    created_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
    CONSTRAINT favorite_pk PRIMARY KEY (favorite_id),
    CONSTRAINT uq_favorite_member_product UNIQUE (member_id, product_id),
    CONSTRAINT fk_favorite_member FOREIGN KEY (member_id)
        REFERENCES member (login_id) ON DELETE CASCADE,
    CONSTRAINT fk_favorite_product FOREIGN KEY (product_id)
        REFERENCES product (product_id) ON DELETE CASCADE
);

CREATE TABLE report (
    report_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    reporter_id VARCHAR2(20 BYTE) NOT NULL,
    target_type VARCHAR2(20 BYTE) NOT NULL,
    target_id NUMBER NOT NULL,
    reason VARCHAR2(100 BYTE) NOT NULL,
    detail CLOB,
    status VARCHAR2(20 BYTE) DEFAULT 'WAITING' NOT NULL,
    created_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
    processed_at TIMESTAMP(6),
    CONSTRAINT report_pk PRIMARY KEY (report_id),
    CONSTRAINT fk_report_reporter FOREIGN KEY (reporter_id)
        REFERENCES member (login_id),
    CONSTRAINT chk_report_target_type CHECK (target_type IN ('PRODUCT', 'MEMBER', 'CHAT')),
    CONSTRAINT chk_report_status CHECK (status IN ('WAITING', 'DONE', 'REJECTED'))
);

COMMIT;
