CREATE TABLE report (
    report_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_id VARCHAR2(20) NOT NULL,
    target_type VARCHAR2(20) NOT NULL,
    target_id NUMBER NOT NULL,
    reason VARCHAR2(100) NOT NULL,
    detail CLOB,
    status VARCHAR2(20) DEFAULT 'WAITING' NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    processed_at TIMESTAMP,
    CONSTRAINT fk_report_reporter FOREIGN KEY (reporter_id) REFERENCES member(login_id),
    CONSTRAINT chk_report_target_type CHECK (target_type IN ('PRODUCT', 'MEMBER', 'CHAT', 'CAFE', 'CAFE_POST', 'CAFE_COMMENT')),
    CONSTRAINT chk_report_status CHECK (status IN ('WAITING', 'DONE', 'REJECTED'))
);
