-- 커뮤니티 신고 처리 이력 컬럼 추가
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE report ADD processed_by VARCHAR2(50 BYTE)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE report ADD action_type VARCHAR2(30 BYTE)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE report ADD admin_memo VARCHAR2(1000 BYTE)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE report ADD CONSTRAINT fk_report_processed_by FOREIGN KEY (processed_by) REFERENCES admin(login_id)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2275 THEN RAISE; END IF;
END;
/

COMMIT;
